name: Generate snake

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: gabrielogregorio
          outputs: |
            dist/github-snake.gif?palette=github-dark&color_snake=#3cb2ac&color_dots=#ebedf0,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
